from python:2.7

RUN echo "deb http://ftp.uk.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y ffmpeg && \
    pip install --no-cache-dir boto3
